config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /fr|en/ do
    root :to => 'packs#index'
    resources :packs, only: [:show, :index]
    resources :orders, only: [:new, :show, :create, :index] do
      collection do
        get :price
      end
    end
  end

  get '/login', to: 'admin/sessions#new'
  delete '/logout', to: 'admin/sessions#destroy'

  namespace :admin do
    root :to => 'packs#index'
    resources :orders
    resources :users, only: [:show, :edit, :update]
    resources :packs
    resources :sessions, only: [:new, :create]

  end

end

app/models/pack.rb
class Pack < ActiveRecord::Base
  has_many :orders

  paginates_per 10

  has_attached_file :image,
    default_url: "/missing_images/:style/missing.png",
    styles: {
      medium: "300x300>",
      thumb: "100x100>"
    }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :title, presence: true
  validates :description, presence: true

  include OrderProperties

  translates :title, :description
  globalize_accessors attributes: [:title, :description]

  def price
    PriceCalculation.new(self).price
  end
end

app/controllers/admin/packs_controller.rb
class Admin::PacksController < AdminController
  before_action :find_pack, only: [:show, :edit, :update, :destroy]

  def index
    @packs = Pack.all.page(params[:page])
  end

  def new
    @pack = Pack.new
  end

  def edit
  end

  def create
    @pack = Pack.new(pack_params)
    if @pack.save
      redirect_to admin_packs_path, notice: t('admin.packs.messages.new')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @pack.update(pack_params)
      redirect_to admin_packs_path, notice: t('admin.packs.messages.edit')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @pack.destroy
    redirect_to admin_packs_url, notice: t('admin.packs.messages.destroy')
  end

  private
  def find_pack
    @pack = Pack.find(params[:id])
  end

  def pack_params
    params.require(:pack).permit(*Pack.globalize_attribute_names, :image, :quantity,
      :format, :ingraving, :vinyl_colors, :label, :external_sleeve, :sleeve, :packaging, :weight)
  end
end

app/controllers/packs_controller.rb
class PacksController < PublicController
  before_action :find_pack, only: [:show]

  def index
    @packs = Pack.all
  end

  def show
  end

  private

  def find_pack
    @pack = Pack.find(params[:id])
  end

  def pack_params
    params.require(:pack).permit(:title, :description, :format)
  end
end

app/views/admin/packs/_form.html.erb
<%= bootstrap_form_for([:admin, @pack], html: { class: 'form' }) do |f| %>
  <div class="pack-form">
    <div class="form-group">
      <ul class="nav nav-tabs">
        <% I18n.available_locales.each do |locale| %>
          <li class="<%= 'active' if locale == :fr %>"><a data-toggle="tab" href="#<%= locale %>"><%= t("#{locale}_name") %></a></li>
        <% end %>
      </ul>
      <div class="tab-content">
        <% I18n.available_locales.each do |locale| %>
          <div id="<%= locale %>" class="tab-pane fade <%= 'in active' if locale == :fr %>">
            <%= f.text_field "title_#{locale}" , class: "form-control" %>
            <%= f.text_area "description_#{locale}", class: "form-control" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= f.select :quantity, quantity_attributes_for_select, {} ,{ class: 'form-control', data: { role: "quantity"}} %>
      </div>
      <div class="col-xs-12 col-sm-6">
        <%= f.select :format, format_attributes_for_select, {} ,{ class: 'form-control', data: { role: "format"}} %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= f.select :ingraving, options_for_select(ingraving_attributes_for_select, selected: @pack.ingraving), {} ,{ class: 'form-control' }%>
      </div>
      <div class="col-xs-12 col-sm-6">
        <%= f.select :vinyl_colors, options_for_select(vinyl_colors_attributes_for_select, selected: @pack.vinyl_colors), {} ,{ class: 'form-control' }%>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= f.select :external_sleeve, options_for_select(external_sleeve_attributes_for_select, selected: @pack.external_sleeve), {} ,{ class: 'form-control' }%>
      </div>
      <div class="col-xs-12 col-sm-6">
        <%= f.select :sleeve, options_for_select(sleeve_attributes_for_select, selected: @pack.sleeve), {} ,{ class: 'form-control' }%>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= f.select :packaging, options_for_select(packaging_attributes_for_select, selected: @pack.packaging), {} ,{ class: 'form-control' }%>
      </div>
      <div class="col-xs-12 col-sm-6">
        <%= f.select :weight, options_for_select(weight_attributes_for_select, selected: @pack.weight), {} ,{ class: 'form-control' }%>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <%= f.select :label, options_for_select(label_attributes_for_select, selected: @pack.label), {} ,{ class: 'form-control' }%>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <%= f.file_field :image, id: "upload-image", data: { role: 'upload-image' }%>
        <%= image_tag @pack.image.url(:medium), id: "upload-preview", data: { role: 'upload-preview' }%>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit t('admin.packs.action.new'), class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/packs/edit.html.erb
<h2><%= t('admin.packs.edit.title') %></h2>

<%= render 'form' %>

<%= link_to t('admin.packs.action.show'), admin_packs_path %> |
<%= link_to t('admin.packs.action.back'), admin_packs_path %>

app/views/admin/packs/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2><%= t('admin.packs.index.title') %></h2></div>
  <div class="add-pack">
    <%= link_to "" , new_admin_pack_path, class:"fa fa-plus-square" %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th><%= Pack.human_attribute_name(:title) %></th>
        <th><%= Pack.human_attribute_name(:description) %></th>
        <th><%= Pack.human_attribute_name(:format) %></th>
        <th><%= Pack.human_attribute_name(:price) %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @packs.each do |pack| %>
        <tr>
          <td><%= pack.title %></td>
          <td><%= pack.description %></td>
          <td><%= pack.format %></td>
          <td><%= pack.price %></td>
          <td><%= image_tag pack.image.url(:thumb) %></td>
          <td><%= link_to t('admin.packs.action.edit'), edit_admin_pack_path(pack) %></td>
          <td><%= link_to t('admin.packs.action.destroy'), admin_pack_path(pack.id), method: :delete, data: { confirm: t('admin.packs.action.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center">
    <nav><ul class="pagination pagination-sm"><%= paginate @packs %></ul></nav>
  </div>
</div>
<br>

app/views/admin/packs/new.html.erb
<h2><%= t('admin.packs.new.title') %></h2>
<%= render 'form' %>