config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /fr|en/ do
    root :to => 'packs#index'
    resources :packs, only: [:show, :index]
    resources :orders, only: [:new, :show, :create, :index] do
      collection do
        get :price
      end
    end
  end

  get '/login', to: 'admin/sessions#new'
  delete '/logout', to: 'admin/sessions#destroy'

  namespace :admin do
    root :to => 'packs#index'
    resources :orders
    resources :users, only: [:show, :edit, :update]
    resources :packs
    resources :sessions, only: [:new, :create]

  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  delegate :price, :price_for, to: :price_calculation

  belongs_to :pack
  belongs_to :client

  accepts_nested_attributes_for :client

  paginates_per 10

  attr_accessor :is_quote

  validates :artist_name, presence: true, unless: :is_quote
  validates :album_title, presence: true, unless: :is_quote
  validates :label_name, presence: true, unless: :is_quote
  validates :num_cat, presence: true, unless: :is_quote

  include OrderProperties

  def self.new_from_pack(pack)
    new(pack: pack, format: pack.format, quantity: pack.quantity,
      client: Client.new, is_quote: true, ingraving: pack.ingraving,
      vinyl_colors: pack.vinyl_colors, label: pack.label,
      external_sleeve: pack.external_sleeve, sleeve: pack.sleeve,
      packaging: pack.packaging, weight: pack.weight)
  end

  def price_calculation
    @price_calculation ||= PriceCalculation.new(self)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :find_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.order(:id).page(params[:page])
  end

  def edit
  end

  def update
    if @order.update(order_params)
      redirect_to admin_orders_path, notice: t('admin.orders.messages.edit')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @order.destroy
    redirect_to admin_orders_url, notice: t('admin.orders.messages.destroy')
  end

  private

  def find_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit( :artist_name, :album_title, :label_name, :num_cat,
      :delivery_price, :status, :total_price, :quantity, :format, :ingraving, :vinyl_colors,
      :label, :external_sleeve, :sleeve, :packaging, :weight, :pack_id, client_attributes: [:id, :email])
  end
end

app/controllers/orders_controller.rb
class OrdersController < PublicController
  def index
    redirect_to packs_path
  end

  def show
    @order = Order.find(params[:id])
    respond_to do |format|
      format.pdf { render :layout => false } # Add this line
    end
  end

  def new
    @order = Order.new_from_pack(find_pack)
  end

  def price
    render json: { price: Order.new(price_params).price }
  end


  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to order_path(@order, format: 'pdf')
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def find_pack
    Pack.find(params[:pack_id] || params[:order][:pack_id])
  end

  def price_params
    params.require(:order).permit(:quantity ,:format ,:ingraving, :vinyl_colors, :external_sleeve, :sleeve, :packaging, :weight, :label)
  end

  def order_params
    filtered_params.require(:order).permit(*order_permitted_attributes, client_attributes: client_permitted_attributes)
  end

  def order_permitted_attributes
    [:artist_name, :album_title, :label_name, :num_cat, :delivery_price, :status,
     :total_price, :quantity, :format, :ingraving, :vinyl_colors, :label, :external_sleeve,
     :sleeve, :packaging, :weight, :pack_id, :is_quote]
  end

  def client_permitted_attributes
    [:id, :email, :is_quote]
  end

  def filtered_params
    params[:order][:is_quote] = params[:order][:is_quote] == 'true'
    params[:order][:client_attributes][:is_quote] = params[:order][:is_quote]
    params
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def format_attributes_for_select
    Order.formats.keys.map do |format|
      [I18n.t("public.orders.formats.#{format}"), format]
    end
  end

  def quantity_attributes_for_select
    Order.quantities.keys.map do |quantity|
      [I18n.t("public.orders.quantities.#{quantity}"), quantity]
    end
  end

  def ingraving_attributes_for_select
    Order.ingravings.keys.map do |ingraving|
      [I18n.t("public.orders.ingravings.#{ingraving}"), ingraving]
    end
  end

  def vinyl_colors_attributes_for_select
    Order.vinyl_colors.keys.map do |vinyl_colors|
      [I18n.t("public.orders.vinyls_colors.#{vinyl_colors}"), vinyl_colors]
    end
  end

  def label_attributes_for_select
    Order.labels.keys.map do |label|
      [I18n.t("public.orders.labels.#{label}"), label]
    end
  end

  def external_sleeve_attributes_for_select
    Order.external_sleeves.keys.map do |external_sleeve|
      [I18n.t("public.orders.external_sleeves.#{external_sleeve}"), external_sleeve]
    end
  end

  def sleeve_attributes_for_select
    Order.sleeves.keys.map do |sleeve|
      [I18n.t("public.orders.sleeves.#{sleeve}"), sleeve]
    end
  end

  def packaging_attributes_for_select
    Order.packagings.keys.map do |packaging|
      [I18n.t("public.orders.packagings.#{packaging}"), packaging]
    end
  end

  def weight_attributes_for_select
    Order.weights.keys.map do |weight|
      [I18n.t("public.orders.weights.#{weight}"), weight]
    end
  end

  def status_attributes_for_select
    Order.statuses.keys.map do |status|
      [I18n.t("public.orders.statuses.#{status}"), status]
    end
  end
end

app/views/admin/orders/_form.html.erb
<%= bootstrap_form_for [:admin, @order], html: { class: 'form' } do |f| %>

  <%= f.hidden_field :pack_id %>

<h2 class="order-title">Details commande</h2>
  <div class="order-form">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= f.select :quantity, quantity_attributes_for_select, {} ,{ class: 'form-control', data: { role: "quantity"}} %>
      </div>
      <div class="col-xs-12 col-sm-6">
        <%= f.select :format, format_attributes_for_select, {} ,{ class: 'form-control', data: { role: "format"}} %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= f.select :ingraving, ingraving_attributes_for_select, {} ,{ class: 'form-control' } %>
      </div>
      <div class="col-xs-12 col-sm-6">
        <%= f.select :vinyl_colors, vinyl_colors_attributes_for_select, {}, { class: 'form-control'} %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= f.select :external_sleeve, external_sleeve_attributes_for_select, {}, { class: 'form-control'} %>
      </div>
      <div class="col-xs-12 col-sm-6">
        <%= f.select :sleeve, sleeve_attributes_for_select, {}, { class: 'form-control'} %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= f.select :packaging, packaging_attributes_for_select, {}, { class: 'form-control'} %>
      </div>
      <div class="col-xs-12 col-sm-6">
        <%= f.select :weight, weight_attributes_for_select, {}, { class: 'form-control'} %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <%= f.select :label, label_attributes_for_select, {}, { class: 'form-control'} %>
      </div>
    </div>
  </div>

  <h2 class="order-title">Informations Artiste</h2>
  <div class="order-form">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= f.text_field :artist_name, class: "form-control" %>
      </div>
      <div class="col-xs-12 col-sm-6">
        <%= f.text_field :album_title, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= f.text_field :label_name, class: "form-control" %>
      </div>
      <div class="col-xs-12 col-sm-6">
        <%= f.number_field :num_cat, class: "form-control" %>
      </div>
    </div>
    <h2 class="order-title">Informations Client</h2>
    <div class="row">
      <div class="col-xs-12">
        <%= f.fields_for :client do |c| %>
          <%= c.text_field :email, class: "form-control" %>
        <% end %>
      </div>
    </div>
    <h2 class="order-title">Status</h2>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <%= f.number_field :delivery_price, class: 'form-control' %>
      </div>
      <div class="col-xs-12 col-sm-6">
        <%= label_tag t('activerecord.attributes.order.total_price') %>
        <%= number_field_tag 'total_price', @order.price + @order.delivery_price, class: 'form-control' %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <%= f.select :status, status_attributes_for_select, {}, { class: 'form-control'} %>
      </div>
    </div>
  </div>
  <div class="order-form">
    <div class="row">
      <div class="col-xs-12 text-center order-btn">
        <%= f.submit t('admin.orders.action.edit'), class: "btn btn-success" %>
      </div>
  </div>
</div>
<% end %>

app/views/admin/orders/edit.html.erb
<h2><%= t('admin.orders.edit.title') %></h2>

<%= render 'form' %>

app/views/admin/orders/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h2><%= t('admin.orders.index.title') %></h2></div>
  <table class="table">
    <thead>
      <tr>
        <th><%= Client.human_attribute_name(:email) %></th>
        <th><%= Order.human_attribute_name(:created_at) %></th>
        <th><%= Order.human_attribute_name(:artist_name) %></th>
        <th><%= Order.human_attribute_name(:album_title) %></th>
        <th><%= Order.human_attribute_name(:label_name) %></th>
        <th><%= Order.human_attribute_name(:status) %></th>
        <th><%= Order.human_attribute_name(:total_price) %></th>
        <th><%= Order.human_attribute_name(:quantity) %></th>
        <th><%= Order.human_attribute_name(:format) %></th>
        <th><%= Order.human_attribute_name(:pack) %></th>
        <th><%= Order.human_attribute_name(:price) %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.try(:client).try(:email) %></td>
          <td><%= l(order.created_at, format: :short) %></td>
          <td><%= order.artist_name %></td>
          <td><%= order.album_title %></td>
          <td><%= order.label_name %></td>
          <td><%= order.status %></td>
          <td><%= order.total_price %></td>
          <td><%= t("public.orders.quantities.#{order.quantity}") %></td>
          <td><%= order.format %></td>
          <td><%= order.pack_id %></td>
          <td><%= order.price %></td>
          <td><%= link_to t('admin.packs.action.edit'), edit_admin_order_path(order) %></td>
          <td><%= link_to t('admin.packs.action.destroy'), admin_order_path(order.id), method: :delete, data: { confirm: t('admin.packs.action.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center">
    <nav><ul class="pagination pagination-sm"><%= paginate @orders %></ul></nav>
  </div>
</div>
<br>

app/views/admin/orders/new.html.erb
<h2><%= t('admin.orders.new.title') %></h2>
<%= render 'form' %>