config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /fr|en/ do
    root :to => 'packs#index'
    resources :packs, only: [:show, :index]
    resources :orders, only: [:new, :show, :create, :index] do
      collection do
        get :price
      end
    end
  end

  get '/login', to: 'admin/sessions#new'
  delete '/logout', to: 'admin/sessions#destroy'

  namespace :admin do
    root :to => 'packs#index'
    resources :orders
    resources :users, only: [:show, :edit, :update]
    resources :packs
    resources :sessions, only: [:new, :create]

  end

end

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top mgv-navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-brand">
      <p>LOGO Admin</p>
    </div>
    <% if current_user %>
      <div id="navbar" class="navbar-collapse collapse">
        <%= link_to "Packs", admin_packs_path, class: "btn btn-success" %>
        <%= link_to "Orders", admin_orders_path, class: "btn btn-success" %>
        <div class="navbar-form navbar-right">
          <% if current_user %>
            <div class="dropdown">
              <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                <%= current_user.email %>
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                <li role="presentation"><%= link_to t('admin.layouts.signed_out'), logout_path, method: :delete %></li>
                <li role="presentation"><%= link_to t('admin.layouts.edit_account'), edit_admin_user_path(current_user.id) %></li>
              </ul>
            </div>
          <% else %>
            <%= link_to "Se connecter", login_path(locale: nil), class: "btn btn-success"  %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/admin/_messages.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <p id="alert"><%= alert %></p>
  </div>
<% end %>